# Generated by Django 3.1.7 on 2021-03-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='username',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
